### ISSUE TITLE
Completely blank Watchlist

### ISSUE THREAD

**Issue by MindlessZ** [ranaldsgift/KefinTweaks#82]
Hello,

I'm running jellyfin 10.11.6 and I've just installed KefinTweaks (and JS Injector, File Transformation, and Custom Tabs) and I see the new watchlist tab up top, but it's a completely blank page. I see in the console an error 

```
[KefinTweaks HeaderTabs] Target tab content not found for index: 2 [headerTabs.js:10:39](https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@v0.4.5/scripts/headerTabs.js)
[KefinTweaks HeaderTabs] Tab clicked: home 2 [headerTabs.js:9:38](https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@v0.4.5/scripts/headerTabs.js)
[KefinTweaks HeaderTabs] No landing preference match found, using tab 0 without updating URL [headerTabs.js:9:38](https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@v0.4.5/scripts/headerTabs.js)
[KefinTweaks HeaderTabs] Set active tab content: 0 [headerTabs.js:9:38](https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@v0.4.5/scripts/headerTabs.js)
[KefinTweaks Watchlist] On watchlist tab, enhancing progress bars with episode details [watchlist.js:16:38](https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@v0.4.5/scripts/watchlist.js)
offset:218.7166748046875 currentStart:0 currentEnd:342 [4113.83b0350d733cb0566fab.chunk.js:1:5672](https://my.jellyfin.server/web/4113.83b0350d733cb0566fab.chunk.js)
[KefinTweaks HeaderTabs] Added click listeners to 3 buttons
```

followed shortly by an `Uncaught Error: Cannot find module './'`

---

I know 10.11.x is unsupported, but I figured I'd open the issue in hopes that it might be a known/recognizable issue (or an easily remedied user error)

Thanks in advance

**Comment by ranaldsgift** [comment]
Hey @MindlessZ I wonder if this is an issue with the registration with Custom Tabs. Can you verify if your Custom Tabs configuration for the Watchlist tab looks like this:

<img width="817" height="356" alt="Image" src="https://github.com/user-attachments/assets/ed2878ac-16ac-433d-908e-c2ef50b05379" />

If it does have the <div class="sections watchlist"></div> then this is not the source of the issue. 

If I remember right, the `Uncaught Error: Cannot find module './'` is a native Jellyfin issue that is present without KT.

Let's start by checking the Custom Tabs configuration and go from there. I'll have more time to think of other potential issues in the meantime.

And for your peace of mind, this is intended to work on 10.11.x and it does work without issues on my 10.11.x dev instance.

Sorry you are experiencing this but I hope we can solve it quickly for you!

**Comment by MindlessZ** [comment]
So idk what changed, but this morning the watchlist is working as expected.

In case it's helpful to you or others, I opened this issue after poking around, clearing cache, trying different browsers, uninstalling and reinstalling, and none of it made a difference. The custom tabs config is correct (and was when I opened the issue).

I can't imagine what I would've done this morning that's different than what I was trying yesterday, but I think we can chalk this up to user error.

Regardless, thanks for the really quick feedback and help

**Comment by gbomacfly** [comment]
I have exactly the same error, but only in chrome on mac. Custom Tabs Settings are correct.


`Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at d (81954.300ea98bc9f7b1557160.chunk.js:1:14867)
    at HTMLDivElement.selectedIndex (81954.300ea98bc9f7b1557160.chunk.js:1:17650)
    at Module.v (81954.300ea98bc9f7b1557160.chunk.js:1:8537)
    at t.value (81954.300ea98bc9f7b1557160.chunk.js:1:2419)
    at 81954.300ea98bc9f7b1557160.chunk.js:1:3637
    at t.value (81954.300ea98bc9f7b1557160.chunk.js:1:5346)
    at HTMLDivElement.<anonymous> (81954.300ea98bc9f7b1557160.chunk.js:1:2213)
    at d (main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2:322666)
    at main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2:324140
d @ 81954.300ea98bc9f7b1557160.chunk.js:1
(anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
v @ 81954.300ea98bc9f7b1557160.chunk.js:1
value @ 81954.300ea98bc9f7b1557160.chunk.js:1
(anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
value @ 81954.300ea98bc9f7b1557160.chunk.js:1
(anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
d @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
Promise.then
value @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
a @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
Promise.then
l @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
c @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
m @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
ri @ node_modules.react-dom.bundle.js?dcafaf8c30924dfb8ad2:2
Ss @ node_modules.react-dom.bundle.js?dcafaf8c30924dfb8ad2:2
(anonymous) @ node_modules.react-dom.bundle.js?dcafaf8c30924dfb8ad2:2
x @ 46967.bundle.js?dcafaf8c30924dfb8ad2:2
P @ 46967.bundle.js?dcafaf8c30924dfb8ad2:2
I.<computed> @ node_modules.core-js.bundle.js?dcafaf8c30924dfb8ad2:1
M @ node_modules.core-js.bundle.js?dcafaf8c30924dfb8ad2:1
P @ node_modules.core-js.bundle.js?dcafaf8c30924dfb8ad2:1Understand this error
watchlist.js:16 `

followed by the `Uncaught Error: Cannot find module './'`

**Comment by gbomacfly** [comment]
Sorry, I think this is better:

```headerTabs.js:9 [KefinTweaks HeaderTabs] onViewPage handler triggered for view: home
headerTabs.js:9 [KefinTweaks HeaderTabs] No tab parameter and no parentId, fetching from display preferences for page: home
headerTabs.js:9 [KefinTweaks HeaderTabs] No landing preference found for landing-home
watchlist.js:16 [KefinTweaks Watchlist] onViewPage handler triggered for view: home
headerTabs.js:9 [KefinTweaks HeaderTabs] Updated URL with tab: 2 https://jellyfin.domain.de/web/#/home?tab=2
headerTabs.js:10 [KefinTweaks HeaderTabs] Target tab content not found for index: 2
WARN @ headerTabs.js:10
handleTabClick @ headerTabs.js:228
headerTabs.js:9 [KefinTweaks HeaderTabs] Tab clicked: home 2
headerTabs.js:9 [KefinTweaks HeaderTabs] No landing preference match found, using tab 0 without updating URL
headerTabs.js:9 [KefinTweaks HeaderTabs] Set active tab content: 0
watchlist.js:16 [KefinTweaks Watchlist] On watchlist tab, enhancing progress bars with episode details
headerTabs.js:9 [KefinTweaks HeaderTabs] Added click listeners to 3 buttons
main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2 Uncaught (in promise) Error: Cannot find module './'
    at main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2:26360
    (anonymous) @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
    Promise.then
    i @ main.jellyfin.bundle.js?dcafaf8c30924dfb8ad2:2
    value @ 81954.300ea98bc9f7b1557160.chunk.js:1
    (anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
    Promise.then
    (anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
    l @ 81954.300ea98bc9f7b1557160.chunk.js:1
    (anonymous) @ 81954.300ea98bc9f7b1557160.chunk.js:1
    setTimeout
    v @ 81954.300ea98bc9f7b1557160.chunk.js:1```

**Comment by gbomacfly** [comment]
Now it works. The reason was the checked checkbox at the JS-Injector "Requires Authentication"
